// Code generated by MockGen. DO NOT EDIT.
// Source: internal/sbi/consumer/consumer.go
//
// Generated by this command:
//
//	mockgen -source=internal/sbi/consumer/consumer.go -destination=internal/sbi/consumer/mock_services_test.go -package=consumer
//

// Package consumer is a generated GoMock package.
package consumer

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSmfServiceClient is a mock of SmfServiceClient interface.
type MockSmfServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSmfServiceClientMockRecorder
}

// MockSmfServiceClientMockRecorder is the mock recorder for MockSmfServiceClient.
type MockSmfServiceClientMockRecorder struct {
	mock *MockSmfServiceClient
}

// NewMockSmfServiceClient creates a new mock instance.
func NewMockSmfServiceClient(ctrl *gomock.Controller) *MockSmfServiceClient {
	mock := &MockSmfServiceClient{ctrl: ctrl}
	mock.recorder = &MockSmfServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmfServiceClient) EXPECT() *MockSmfServiceClientMockRecorder {
	return m.recorder
}

// HTTPClient mocks base method.
func (m *MockSmfServiceClient) HTTPClient() *http.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPClient")
	ret0, _ := ret[0].(*http.Client)
	return ret0
}

// HTTPClient indicates an expected call of HTTPClient.
func (mr *MockSmfServiceClientMockRecorder) HTTPClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPClient", reflect.TypeOf((*MockSmfServiceClient)(nil).HTTPClient))
}

// SubscribeToSmf mocks base method.
func (m *MockSmfServiceClient) SubscribeToSmf(ctx context.Context, smfEndpoint string, opts SmfSubscriptionOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToSmf", ctx, smfEndpoint, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToSmf indicates an expected call of SubscribeToSmf.
func (mr *MockSmfServiceClientMockRecorder) SubscribeToSmf(ctx, smfEndpoint, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToSmf", reflect.TypeOf((*MockSmfServiceClient)(nil).SubscribeToSmf), ctx, smfEndpoint, opts)
}

// UnsubscribeFromSmf mocks base method.
func (m *MockSmfServiceClient) UnsubscribeFromSmf(ctx context.Context, smfEndpoint, subscriptionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeFromSmf", ctx, smfEndpoint, subscriptionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeFromSmf indicates an expected call of UnsubscribeFromSmf.
func (mr *MockSmfServiceClientMockRecorder) UnsubscribeFromSmf(ctx, smfEndpoint, subscriptionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeFromSmf", reflect.TypeOf((*MockSmfServiceClient)(nil).UnsubscribeFromSmf), ctx, smfEndpoint, subscriptionId)
}

// MockMtlfServiceClient is a mock of MtlfServiceClient interface.
type MockMtlfServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMtlfServiceClientMockRecorder
}

// MockMtlfServiceClientMockRecorder is the mock recorder for MockMtlfServiceClient.
type MockMtlfServiceClientMockRecorder struct {
	mock *MockMtlfServiceClient
}

// NewMockMtlfServiceClient creates a new mock instance.
func NewMockMtlfServiceClient(ctrl *gomock.Controller) *MockMtlfServiceClient {
	mock := &MockMtlfServiceClient{ctrl: ctrl}
	mock.recorder = &MockMtlfServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMtlfServiceClient) EXPECT() *MockMtlfServiceClientMockRecorder {
	return m.recorder
}

// HTTPClient mocks base method.
func (m *MockMtlfServiceClient) HTTPClient() *http.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPClient")
	ret0, _ := ret[0].(*http.Client)
	return ret0
}

// HTTPClient indicates an expected call of HTTPClient.
func (mr *MockMtlfServiceClientMockRecorder) HTTPClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPClient", reflect.TypeOf((*MockMtlfServiceClient)(nil).HTTPClient))
}

// SubscribeToMtlf mocks base method.
func (m *MockMtlfServiceClient) SubscribeToMtlf(ctx context.Context, mtlfEndpoint string, opts MtlfSubscriptionOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToMtlf", ctx, mtlfEndpoint, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToMtlf indicates an expected call of SubscribeToMtlf.
func (mr *MockMtlfServiceClientMockRecorder) SubscribeToMtlf(ctx, mtlfEndpoint, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToMtlf", reflect.TypeOf((*MockMtlfServiceClient)(nil).SubscribeToMtlf), ctx, mtlfEndpoint, opts)
}

// UnsubscribeFromMtlf mocks base method.
func (m *MockMtlfServiceClient) UnsubscribeFromMtlf(ctx context.Context, mtlfEndpoint, subscriptionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeFromMtlf", ctx, mtlfEndpoint, subscriptionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeFromMtlf indicates an expected call of UnsubscribeFromMtlf.
func (mr *MockMtlfServiceClientMockRecorder) UnsubscribeFromMtlf(ctx, mtlfEndpoint, subscriptionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeFromMtlf", reflect.TypeOf((*MockMtlfServiceClient)(nil).UnsubscribeFromMtlf), ctx, mtlfEndpoint, subscriptionId)
}
