package context

import (
	"sync"
	"time"
)

// CorrelationIdMapping maps a notifyCorrelationId to the target SUPI
// Per TS 29.564: UPF notifications may not include SUPI, so we use
// the correlationId from the subscription to identify the target UE
type CorrelationIdMapping struct {
	mu sync.RWMutex

	CorrelationId string    // UUID generated by NWDAF at subscription time
	Supi          string    // Target SUPI for this subscription
	NwdafSubId    string    // NWDAF subscription ID (for analytics delivery)
	SmfSubId      string    // SMF subscription ID (for cleanup/unsubscribe)
	SmfEndpoint   string    // SMF endpoint URL
	CreatedAt     time.Time // When mapping was created
}

// --- CorrelationId Mapping Management ---

// StoreCorrelationMapping stores a correlationId -> SUPI mapping
func (c *NWDAFContext) StoreCorrelationMapping(m *CorrelationIdMapping) {
	c.correlationIdMap.Store(m.CorrelationId, m)
}

// GetCorrelationMapping retrieves a mapping by correlationId
func (c *NWDAFContext) GetCorrelationMapping(correlationId string) (*CorrelationIdMapping, bool) {
	if value, ok := c.correlationIdMap.Load(correlationId); ok {
		return value.(*CorrelationIdMapping), true
	}
	return nil, false
}

// GetSupiByCorrelationId retrieves SUPI from correlationId
func (c *NWDAFContext) GetSupiByCorrelationId(correlationId string) (string, bool) {
	if mapping, ok := c.GetCorrelationMapping(correlationId); ok {
		return mapping.Supi, true
	}
	return "", false
}

// DeleteCorrelationMapping removes a single mapping
func (c *NWDAFContext) DeleteCorrelationMapping(correlationId string) {
	c.correlationIdMap.Delete(correlationId)
}

// DeleteCorrelationMappingsByNwdafSubId removes all mappings for a NWDAF subscription
// Called when a subscription is deleted to clean up related mappings
func (c *NWDAFContext) DeleteCorrelationMappingsByNwdafSubId(nwdafSubId string) []string {
	var deletedIds []string
	c.correlationIdMap.Range(func(key, value interface{}) bool {
		mapping := value.(*CorrelationIdMapping)
		if mapping.NwdafSubId == nwdafSubId {
			c.correlationIdMap.Delete(key)
			deletedIds = append(deletedIds, mapping.CorrelationId)
		}
		return true
	})
	return deletedIds
}

// GetCorrelationMappingsByNwdafSubId retrieves all mappings for a NWDAF subscription
func (c *NWDAFContext) GetCorrelationMappingsByNwdafSubId(nwdafSubId string) []*CorrelationIdMapping {
	var mappings []*CorrelationIdMapping
	c.correlationIdMap.Range(func(key, value interface{}) bool {
		mapping := value.(*CorrelationIdMapping)
		if mapping.NwdafSubId == nwdafSubId {
			mappings = append(mappings, mapping)
		}
		return true
	})
	return mappings
}

// ClearCorrelationMappings removes all mappings (for testing or reset)
func (c *NWDAFContext) ClearCorrelationMappings() {
	c.correlationIdMap.Range(func(key, value interface{}) bool {
		c.correlationIdMap.Delete(key)
		return true
	})
}
