// Code generated by MockGen. DO NOT EDIT.
// Source: internal/sbi/server.go (processorAPI portion only)
//
// Generated by this command:
//
//	mockgen -source=internal/sbi/server.go -destination=internal/sbi/mock_interfaces_test.go -package=sbi
//

// Package sbi is a generated GoMock package.
package sbi

import (
	reflect "reflect"

	context0 "github.com/free5gc/nwdaf/internal/context"
	processor "github.com/free5gc/nwdaf/internal/sbi/processor"
	models "github.com/free5gc/openapi/models"
	gomock "go.uber.org/mock/gomock"
)

// MockprocessorAPI is a mock of processorAPI interface.
type MockprocessorAPI struct {
	ctrl     *gomock.Controller
	recorder *MockprocessorAPIMockRecorder
}

// MockprocessorAPIMockRecorder is the mock recorder for MockprocessorAPI.
type MockprocessorAPIMockRecorder struct {
	mock *MockprocessorAPI
}

// NewMockprocessorAPI creates a new mock instance.
func NewMockprocessorAPI(ctrl *gomock.Controller) *MockprocessorAPI {
	mock := &MockprocessorAPI{ctrl: ctrl}
	mock.recorder = &MockprocessorAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprocessorAPI) EXPECT() *MockprocessorAPIMockRecorder {
	return m.recorder
}

// HandleAdrfRetrievalNotify mocks base method.
func (m *MockprocessorAPI) HandleAdrfRetrievalNotify(notifCorrID string, fetchCorrIDs []string, terminationReq bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleAdrfRetrievalNotify", notifCorrID, fetchCorrIDs, terminationReq)
}

// HandleAdrfRetrievalNotify indicates an expected call of HandleAdrfRetrievalNotify.
func (mr *MockprocessorAPIMockRecorder) HandleAdrfRetrievalNotify(notifCorrID, fetchCorrIDs, terminationReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAdrfRetrievalNotify", reflect.TypeOf((*MockprocessorAPI)(nil).HandleAdrfRetrievalNotify), notifCorrID, fetchCorrIDs, terminationReq)
}

// HandleCreateSubscription mocks base method.
func (m *MockprocessorAPI) HandleCreateSubscription(req *models.NnwdafEventsSubscription) (*models.NnwdafEventsSubscription, string, *models.ProblemDetails) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCreateSubscription", req)
	ret0, _ := ret[0].(*models.NnwdafEventsSubscription)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*models.ProblemDetails)
	return ret0, ret1, ret2
}

// HandleCreateSubscription indicates an expected call of HandleCreateSubscription.
func (mr *MockprocessorAPIMockRecorder) HandleCreateSubscription(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCreateSubscription", reflect.TypeOf((*MockprocessorAPI)(nil).HandleCreateSubscription), req)
}

// HandleDaisyCallback mocks base method.
func (m *MockprocessorAPI) HandleDaisyCallback(taskID, modelURL, status, errMsg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleDaisyCallback", taskID, modelURL, status, errMsg)
}

// HandleDaisyCallback indicates an expected call of HandleDaisyCallback.
func (mr *MockprocessorAPIMockRecorder) HandleDaisyCallback(taskID, modelURL, status, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDaisyCallback", reflect.TypeOf((*MockprocessorAPI)(nil).HandleDaisyCallback), taskID, modelURL, status, errMsg)
}

// HandleDeleteSubscription mocks base method.
func (m *MockprocessorAPI) HandleDeleteSubscription(subscriptionID string) *models.ProblemDetails {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDeleteSubscription", subscriptionID)
	ret0, _ := ret[0].(*models.ProblemDetails)
	return ret0
}

// HandleDeleteSubscription indicates an expected call of HandleDeleteSubscription.
func (mr *MockprocessorAPIMockRecorder) HandleDeleteSubscription(subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDeleteSubscription", reflect.TypeOf((*MockprocessorAPI)(nil).HandleDeleteSubscription), subscriptionID)
}

// HandleSmfNotification mocks base method.
func (m *MockprocessorAPI) HandleSmfNotification(notification *models.NsmfEventExposureNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSmfNotification", notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleSmfNotification indicates an expected call of HandleSmfNotification.
func (mr *MockprocessorAPIMockRecorder) HandleSmfNotification(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSmfNotification", reflect.TypeOf((*MockprocessorAPI)(nil).HandleSmfNotification), notification)
}

// HandleUpdateSubscription mocks base method.
func (m *MockprocessorAPI) HandleUpdateSubscription(subscriptionID string, req *models.NnwdafEventsSubscription) (*models.NnwdafEventsSubscription, *models.ProblemDetails) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdateSubscription", subscriptionID, req)
	ret0, _ := ret[0].(*models.NnwdafEventsSubscription)
	ret1, _ := ret[1].(*models.ProblemDetails)
	return ret0, ret1
}

// HandleUpdateSubscription indicates an expected call of HandleUpdateSubscription.
func (mr *MockprocessorAPIMockRecorder) HandleUpdateSubscription(subscriptionID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdateSubscription", reflect.TypeOf((*MockprocessorAPI)(nil).HandleUpdateSubscription), subscriptionID, req)
}

// HandleUpfNotification mocks base method.
func (m *MockprocessorAPI) HandleUpfNotification(notification *processor.UpfNotificationData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpfNotification", notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleUpfNotification indicates an expected call of HandleUpfNotification.
func (mr *MockprocessorAPIMockRecorder) HandleUpfNotification(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpfNotification", reflect.TypeOf((*MockprocessorAPI)(nil).HandleUpfNotification), notification)
}

// InitializeMlModel mocks base method.
func (m *MockprocessorAPI) InitializeMlModel(nwdafSubID string, mlInfo *context0.MlModelInfo, modelURL string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitializeMlModel", nwdafSubID, mlInfo, modelURL)
}

// InitializeMlModel indicates an expected call of InitializeMlModel.
func (mr *MockprocessorAPIMockRecorder) InitializeMlModel(nwdafSubID, mlInfo, modelURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeMlModel", reflect.TypeOf((*MockprocessorAPI)(nil).InitializeMlModel), nwdafSubID, mlInfo, modelURL)
}
