// Code generated by MockGen. DO NOT EDIT.
// Source: internal/sbi/server.go (processorAPI portion only)
//
// Generated by this command:
//
//	mockgen -source=internal/sbi/server.go -destination=internal/sbi/mock_interfaces_test.go -package=sbi
//

// Package sbi is a generated GoMock package.
package sbi

import (
	context "context"
	reflect "reflect"

	models "github.com/free5gc/openapi/models"
	gomock "go.uber.org/mock/gomock"
)

// MockprocessorAPI is a mock of processorAPI interface.
type MockprocessorAPI struct {
	ctrl     *gomock.Controller
	recorder *MockprocessorAPIMockRecorder
}

// MockprocessorAPIMockRecorder is the mock recorder for MockprocessorAPI.
type MockprocessorAPIMockRecorder struct {
	mock *MockprocessorAPI
}

// NewMockprocessorAPI creates a new mock instance.
func NewMockprocessorAPI(ctrl *gomock.Controller) *MockprocessorAPI {
	mock := &MockprocessorAPI{ctrl: ctrl}
	mock.recorder = &MockprocessorAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprocessorAPI) EXPECT() *MockprocessorAPIMockRecorder {
	return m.recorder
}

// HandleAdrfRetrievalNotify mocks base method.
func (m *MockprocessorAPI) HandleAdrfRetrievalNotify(notifCorrID string, fetchCorrIDs []string, terminationReq bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleAdrfRetrievalNotify", notifCorrID, fetchCorrIDs, terminationReq)
}

// HandleAdrfRetrievalNotify indicates an expected call of HandleAdrfRetrievalNotify.
func (mr *MockprocessorAPIMockRecorder) HandleAdrfRetrievalNotify(notifCorrID, fetchCorrIDs, terminationReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAdrfRetrievalNotify", reflect.TypeOf((*MockprocessorAPI)(nil).HandleAdrfRetrievalNotify), notifCorrID, fetchCorrIDs, terminationReq)
}

// HandleCreateSubscription mocks base method.
func (m *MockprocessorAPI) HandleCreateSubscription(ctx context.Context, req *models.NnwdafEventsSubscription) (*models.NnwdafEventsSubscription, string, *models.ProblemDetails) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCreateSubscription", ctx, req)
	ret0, _ := ret[0].(*models.NnwdafEventsSubscription)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*models.ProblemDetails)
	return ret0, ret1, ret2
}

// HandleCreateSubscription indicates an expected call of HandleCreateSubscription.
func (mr *MockprocessorAPIMockRecorder) HandleCreateSubscription(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCreateSubscription", reflect.TypeOf((*MockprocessorAPI)(nil).HandleCreateSubscription), ctx, req)
}

// HandleDeleteSubscription mocks base method.
func (m *MockprocessorAPI) HandleDeleteSubscription(subscriptionID string) *models.ProblemDetails {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDeleteSubscription", subscriptionID)
	ret0, _ := ret[0].(*models.ProblemDetails)
	return ret0
}

// HandleDeleteSubscription indicates an expected call of HandleDeleteSubscription.
func (mr *MockprocessorAPIMockRecorder) HandleDeleteSubscription(subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDeleteSubscription", reflect.TypeOf((*MockprocessorAPI)(nil).HandleDeleteSubscription), subscriptionID)
}

// HandleUpdateSubscription mocks base method.
func (m *MockprocessorAPI) HandleUpdateSubscription(ctx context.Context, subscriptionID string, req *models.NnwdafEventsSubscription) (*models.NnwdafEventsSubscription, *models.ProblemDetails) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdateSubscription", ctx, subscriptionID, req)
	ret0, _ := ret[0].(*models.NnwdafEventsSubscription)
	ret1, _ := ret[1].(*models.ProblemDetails)
	return ret0, ret1
}

// HandleUpdateSubscription indicates an expected call of HandleUpdateSubscription.
func (mr *MockprocessorAPIMockRecorder) HandleUpdateSubscription(ctx, subscriptionID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdateSubscription", reflect.TypeOf((*MockprocessorAPI)(nil).HandleUpdateSubscription), ctx, subscriptionID, req)
}
