info:
  version: 1.0.0
  description: NWDAF-B analytics provider and federated learning client

configuration:
  nwdafName: NWDAF-B
  nfInstanceId: "22222222-2222-4222-8222-222222222222"
  sbi:
    scheme: http
    registerIPv4: 127.0.0.1
    bindingIPv4: 127.0.0.1
    port: 8180
    tls:
      pem: cert/nwdaf.pem
      key: cert/nwdaf.key
  nrfRegistrationEnabled: true
  nrfUri: http://127.0.0.10:8000
  nrfCertPem: cert/nrf.pem

  serviceNameList:
    - nnwdaf-eventssubscription
    - nnwdaf-mlmodelmonitor

  nwdafInfo:
    nwdafEvents:
      - UE_COMMUNICATION
    mlAnalyticsList:
      - mlAnalyticsIds:
          - UE_COMMUNICATION
        trackingAreaList:
          - plmnId:
              mcc: "466"
              mnc: "92"
            tac: "000002"
        mlModelInterInfo:
          vendorList:
            - "001122"
        flCapabilityType: FL_CLIENT
        nfTypeList:
          - UPF

  anlf:
    server:
      bindingIPv4: 127.0.0.1
      registerIPv4: 127.0.0.1
      port: 8190
  mtlf:
    server:
      bindingIPv4: 127.0.0.1
      registerIPv4: 127.0.0.1
      port: 8191
  anlfBackend:
    enabled: true
    endpoint: http://127.0.0.1:9193
    requestTimeout: 35
  mtlfBackend:
    enabled: true
    endpoint: http://127.0.0.1:9192
    requestTimeout: 35

logger:
  enable: true
  level: info
  reportCaller: false
