info:
  version: 1.0.0
  description: NWDAF-C model provider and federated learning server

configuration:
  nwdafName: NWDAF-C
  nfInstanceId: "33333333-3333-4333-8333-333333333333"
  sbi:
    scheme: http
    registerIPv4: 127.0.0.1
    bindingIPv4: 127.0.0.1
    port: 8280
    tls:
      pem: cert/nwdaf.pem
      key: cert/nwdaf.key
  nrfRegistrationEnabled: true
  nrfUri: http://127.0.0.10:8000
  nrfCertPem: cert/nrf.pem

  serviceNameList:
    - nnwdaf-mlmodelprovision
    - nnwdaf-mlmodelmonitor

  nwdafInfo:
    mlAnalyticsList:
      - mlAnalyticsIds:
          - UE_COMMUNICATION
        mlModelInterInfo:
          vendorList:
            - "001122"
        flCapabilityType: FL_SERVER

  anlf:
    server:
      bindingIPv4: 127.0.0.1
      registerIPv4: 127.0.0.1
      port: 8290
  mtlf:
    server:
      bindingIPv4: 127.0.0.1
      registerIPv4: 127.0.0.1
      port: 8291
  anlfBackend:
    enabled: false
  mtlfBackend:
    enabled: true
    endpoint: http://127.0.0.1:9292
    requestTimeout: 35

logger:
  enable: true
  level: info
  reportCaller: false
